- name: Setup Spack on control node
  tags: setup
  become: true
  hosts: local
  connection: local

  tasks:
    - name: Clone spack to control node
      ansible.builtin.git:
        repo: https://github.com/spack/spack.git
        depth: 2
        dest: /opt/spack

    - name: Add spack to control node profile
      copy:
        dest: /etc/profile.d/spack.sh
        content: |
          export SPACK_ROOT=/opt/spack
          source $SPACK_ROOT/share/spack/setup-env.sh
        mode: '0644'

    - name: Activate profile.d
      ansible.builtin.shell: source /etc/profile.d/spack.sh

    - name: Create spack-packages directory
      file:
        path: /opt/spack-packages
        state: directory

    - name: Activate nfs service
      ansible.builtin.shell: systemctl start rpcbind nfs-server

    - name: Export /opt/spack-packages to NFS
      lineinfile:
        path: /etc/exports
        line: "/opt/spack-packages 10.0.20.0/24(rw,no_root_squash)"
        create: yes

    - name: Reload NFS exports
      command: exportfs -ra


- name: Create mounts
  tags: mount
  become: true
  hosts: compute

  tasks:
    - name: Create mount points
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /opt/spack
        - /opt/spack-packages

    - name: Mount spack to nodes
      mount:
        src: "10.0.20.1:/opt/spack"
        path: /opt/spack
        fstype: nfs
        opts: rw,hard,intr
        state: mounted

    - name: Mount spack packages to nodes
      mount:
        src: "10.0.20.1:/opt/spack-packages"
        path: /opt/spack-packages
        fstype: nfs
        opts: rw,hard,intr
        state: mounted

    - name: Add spack to node profiles
      copy:
        dest: /etc/profile.d/spack.sh
        content: |
          export SPACK_ROOT=/opt/spack
          source $SPACK_ROOT/share/spack/setup-env.sh
        mode: '0644'

- name: Install lmod
  tags: install_lmod
  hosts: local
  connection: local

  tasks:
    - name: Spack Install Lmod
      ansible.builtin.shell: spack install lmod

    - name: Load lmod
      ansible.builtin.shell: spack load lmod

    - name: Store lmod path
      command: spack location -i lmod
      register: lmod_path
      changed_when: false

    - name: Set lmod path as global
      set_fact:
        lmod_init_path: "{{ lmod_path.stdout }}"


- name: Sync Spack to nodes
  tags: sync
  become: true
  hosts: compute

  tasks:
    - name: Change bashrc, activate env
      blockinfile:
        path: /root/.bashrc
        marker: "# {mark} SPACK SETUP"
        block: |
          source {{ hostvars['localhost']['lmod_init_path']  }}/lmod/9.1.2/init/bash
          export SPACK_ROOT=/opt/spack
          source /opt/spack/share/spack/setup-env.sh
          export MODULEPATH=/opt/spack/share/spack/lmod/linux-rocky9-x86_64/Core
        create: yes

    - name: Source bashrc
      ansible.builtin.shell: "source /root/.bashrc"

    - name: Check spack env
      ansible.builtin.shell: "spack env status"
      register: spack_env_status

    - name: Display env status
      ansible.builtin.debug:
        var: spack_env_status.stdout_lines


